apiVersion: v1
kind: Service
metadata:
  name: rauloliveira-playlist-recommender-service
spec:
  selector:
    app: rauloliveira-playlist-recommender
  ports:
    - protocol: TCP
      port: 32212
      targetPort: 32212
      nodePort: 30100
  type: NodePort
